name: Compile and Deploy LaTeX Documents

description: GitHub Action to compile and deploy LaTeX documents

inputs:
    paper:
      description: 'space-separated list of LaTeX files to compile'
      type: string
      required: true

runs:
  using: "composite"
  steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for versioning

    - name: Setup environment variables
      shell: bash
      run: |
        echo "TIMESTAMP=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

    - name: Validate input files
      shell: bash
      run: |
        for f in ${{ inputs.paper }}; do
          if [ ! -f "$f" ]; then
            echo "Error: File $f not found!"
            exit 1
          fi
        done

    - name: Download FoilTex
      shell: bash
      run: |
        curl -OL https://mirrors.ctan.org/macros/latex/contrib/foiltex.zip
        unzip foiltex.zip
        mv foiltex/* .

    - name: Compile LaTeX documents
      uses: xu-cheng/latex-action@v4
      with:
        root_file: ${{ inputs.paper }}
        pre_compile: "latex foiltex.ins"
        work_in_root_file_dir: true
      env:
        TEXINPUTS: ".:..:"

    - name: Create deploy directories
      shell: bash
      run: |
        mkdir -p publish
        for f in ${{ inputs.paper }}; do
          cp "${f%.tex}.pdf" publish
        done

    - name: Generate compilation report
      shell: bash
      run: |
        {
          echo "# LaTeX Compilation Report"
          echo "Generated: $(date)"
          echo "## Compiled Documents"
          for f in publish/*.pdf; do
            echo "- $(basename $f)"
            echo "  - Size: $(ls -lh "$f" | awk '{print $5}')"
            echo "  - SHA256: $(sha256sum "$f" | cut -d' ' -f1)"
          done
        } > publish/compilation_report.md

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: draft
        folder: publish
        commit-message: "Build: ${{ env.TIMESTAMP }} [skip ci]"
        clean: true
        single-commit: false